#ifndef RAG_BUILDER_CORPUS_AGGREGATOR_H
#define RAG_BUILDER_CORPUS_AGGREGATOR_H

#include "module.h"

#define RB_CORPUS_AGGREGATOR_MODULE_ID       "RB-CORPUS-AGGREGATOR"
#define RB_CORPUS_AGGREGATOR_MODULE_NAME     "Corpus Aggregator"

#define RB_CORPUS_AGGREGATOR_VERSION_MAJOR   0
#define RB_CORPUS_AGGREGATOR_VERSION_MINOR   3
#define RB_CORPUS_AGGREGATOR_VERSION_PATCH   0

#define RB_CORPUS_AGGREGATOR_EXECUTION_STAGE 400

#define RB_CORPUS_AGGREGATOR_INPUT_SUFFIX    ".corpus.json"
#define RB_CORPUS_AGGREGATOR_OUTPUT_NAME     "kb.corpus.json"
#define RB_CORPUS_AGGREGATOR_TEMP_NAME       "kb.corpus.json.tmp"

#define RB_CORPUS_AGGREGATOR_FORMAT          "STN-LABZ-RAG-KB-CORPUS"
#define RB_CORPUS_AGGREGATOR_FORMAT_VERSION  1

#define RB_CORPUS_AGGREGATOR_ID_MAX          128
#define RB_CORPUS_AGGREGATOR_SHA256_HEX      65
#define RB_CORPUS_AGGREGATOR_PATH_MAX        RB_MODULE_PATH_MAX
#define RB_CORPUS_AGGREGATOR_MAX_CORPORA     4096
#define RB_CORPUS_AGGREGATOR_MAX_INDEX       4096

#define RB_CORPUS_AGGREGATOR_POLICY_INDEX_PATH \
    "C:\\stn-labz\\policies\\policy.index.json"

#define RB_CORPUS_AGGREGATOR_POLICY_CHAINLOG_PATH \
    "C:\\stn-labz\\policies\\policy.index.json.chainlog"

#endif
